### ISSUE TITLE
[Bug report & fix] the location of driverless printer is removed after reboot.

### ISSUE THREAD

**Issue by cchoongh** [OpenPrinting/cups-browsed#16]
**OS**: Debian buster
**CUPS Version**: 2.2.10

Hi, please understand that I'm not a native speaker.

I think the code below should be deleted.
https://github.com/OpenPrinting/cups-filters/blob/7999624bd2d2e3297c44f88d7070f6f44f6db31d/utils/cups-browsed.c#L8606-L8608

Because,
1) the `printer-location` option is loaded to `p->options` at
https://github.com/OpenPrinting/cups-filters/blob/7999624bd2d2e3297c44f88d7070f6f44f6db31d/utils/cups-browsed.c#L8279-L8281
2) after that, `p->options` is copied to `options` at `line 8622 ~ 8627` and encoded to IPP request at `line 8628 ~ 8630`.
https://github.com/OpenPrinting/cups-filters/blob/7999624bd2d2e3297c44f88d7070f6f44f6db31d/utils/cups-browsed.c#L8622-L8630

But, If the `printer-location` option was added to IPP request in advance like `line 8606 ~ 8608`,
the `printer-location` option is ignored at the `cupsEncodeOptions2` fuction(`line 8628 ~ 8630`)
because it is in IPP request already.

As a result, after reboot, the `printer-location` value in `/var/cache/cups/cups-browsed-options-*` is became empty
because, from what I've seen so far, the `p->location` is always empty string.

(and I also think this should be deleted too, because of needless
https://github.com/OpenPrinting/cups-filters/blob/7999624bd2d2e3297c44f88d7070f6f44f6db31d/utils/cups-browsed.c#L8618-L8620)

**Comment by tillkamppeter** [comment]
Fixed via commit eae7971. 

Thank you very much Edgar Fuß!

**Comment by tillkamppeter** [comment]
Also fixed in the 1.x branch, commit https://github.com/OpenPrinting/cups-filters/commit/d72184e7
