### ISSUE TITLE
No destination host name supplied by cups-browsed for printer

### ISSUE THREAD

**Issue by mgedmin** [OpenPrinting/cups-browsed#23]
Today I cannot print from my Ubuntu 20.10 laptop.  The printer is detected, a print job gets created, stays active for 60 seconds, then goes into waiting.  /var/log/cups/errorr_log has

    E [24/Nov/2021:14:34:36 +0200] [Job 69] Bad value (0) for orientation-requested, using 0 degrees

at the time when the job is first created, then

    E [24/Nov/2021:14:35:36 +0200] [Job 69] No destination host name supplied by cups-browsed for printer \"HP_Color_LaserJet_MFP_M477fdw_15A597_\", is cups-browsed running?
    W [24/Nov/2021:14:35:36 +0200] [Job 69] Backend returned status 4 (stop printer)

Printing worked fine just a few days ago, with the same Ubuntu version and the same printers.  I'm not sure what changed.

https://github.com/OpenPrinting/cups-filters/issues/97#issuecomment-729612669 suggests creating an issue here.

> Please check whether at the time of printing cups-browsed is actually running, as cups-browsed tells the job to which destination to go

cups-browsed is running. restarting cups-browsed doesn't make the problem go away.

> Which version of cups-filters do you have

1.28.10-2

> How many print queues does cups-browsed generate on your system (the ones with implicitclass:/... in the output of lpstat -v).

Two, which is correct: the printer advertises itself over DNS-SD, and there's a local server (fridge.lan) with a CUPS queue for the same printer.  Printing to either queue fails in (almost) the same way; the only difference is that only one of the two queues produces the "Bad value (0) for orientation-requested" error.

lpstat -v shows

```
$ lpstat -v
device for HP_Color_LaserJet_MFP_M477fdw_15A597_: implicitclass://HP_Color_LaserJet_MFP_M477fdw_15A597_/
device for HP_Color_LaserJet_MFP_M477fdw_fridge: implicitclass://HP_Color_LaserJet_MFP_M477fdw_fridge/
device for ML-1640-Series: usb://Samsung/ML-1640%20Series?serial=144QBAAS601512F.
```

(the USB printer is currently disconnected and is irrelevant to this bug report)

> Please create an issue report here with /etc/cups/cupsd.conf and /etc/cups/cups-browsed.conf attached.

- [cupsd.conf.txt](https://github.com/OpenPrinting/cups-filters/files/7595679/cupsd.conf.txt)
- [cups-browsed.conf.txt](https://github.com/OpenPrinting/cups-filters/files/7595681/cups-browsed.conf.txt)

(I've made two changes to cups-browsed.conf, compared to stock ubuntu config: removed `cups` from `BrowseLocalProtocols`, and uncommented `DebugLogging file stderr`.)

Also, here's /var/log/cups/cups-browsed_log after I enabled debug logging and restarted cups-browsed, then tried printing.

[cups-browsed_log.txt](https://github.com/OpenPrinting/cups-filters/files/7595691/cups-browsed_log.txt)

Other bug reports had questions about Avahi version, so

```
avahi-resolve --version
avahi-resolve 0.8
```

I can ping both fridge.local and cream.local, i.e. DNS-SD name resolution works fine on the system.  (Besides, cups-browserd _detects_ the printers fine, so it must be seeing mDNS packets).

I'm not sure how to interpret the cups-browsed_log.  The "Remote printer overview" section is interesting, particularly where it says things like `cream.local, IP not determined`.  The only things logged during the actual print job execution and failure are printer state change notifications that don't seem to be saying anything.

I wish I had debug logging enabled from when printing worked fine, so I could see what differs between now and then...

**Comment by tillkamppeter** [comment]
I have found a solution for this, please try it out, current GIT master of cups-browsed (2.x, not cups-filters): 57d9351ea4

As queues with `implicitclass://...` device URI are always created by cups-browsed and do not work without cups-browsed I let cups-browsed consider these always as created by cups-browsed, regardless of whether they have the `cups-browsed=true` attribute.

I have also changed the behavior when a queue created by cups-browsed gets externally overwritten. Such queues only get released by cups-browsed and replaced by a differently named queue if the `implicitclass://...` device URI is replaced by something else. If the device URI stays intact and only the PPD is modified, we recover the original PPD and keep the queue.

This way we will never have `implicitclass://...` queues without supervision by cups-browsed ...

So please test ...

**Comment by shaib** [comment]
In case anyone else still encounters this:
I had the problem. I checked the `/etc/cups/printers.conf` and my printer had 
```
Option cups-browsed true
```
but it was the [angry, down-voted comment](https://github.com/OpenPrinting/cups-browsed/issues/23#issuecomment-1841882579) that led me to a workaround: 
```console
sudo systemctl restart avahi-daemon
```
Followed by restarting `cups` and `cups-browsed`, and suddenly the printer is printing.
