### ISSUE TITLE
VM incasing for printers (original thread locked before I could post this)

### ISSUE THREAD

**Issue by awsdert** [OpenPrinting/cups-browsed#43]
Related to https://github.com/OpenPrinting/cups-browsed/issues/36

The basic idea is that you use tiny linux, damn small linux or similar, doesn't matter which and use that within container VMs to host printers and their scripts in. If an attacker damages the VM so be it, user land is still safe.

The hosted printers will just have their IO put in a user land friendly format via localhost or shared directory or something else, I'm sure you can work out the details of that better than a rando user like I can.

The little latency that this would introduce is likely going to be unnoticeable by the user and not a big deal as a result. As for VM drive and ram I'm sure it goes without saying that you choose something as small as possible.

Once all that background setup is done you can just split issue between VM stuff in which anything can and will be in root mode (since there's no explicit need to have a dedicated user for the VMs) and the user land stuff that ONLY looks for printers using whatever new port and protocol you decide on.

**Edit:** Just in case it wasn't obvious the VMs should by default not run constantly and there should be an option to configure a VM to do so for offices, stores and similar cases where the printers are frequently used

**Comment by michaelrsweet** [comment]
@awsdert So when it comes to cups-browsed, *it* isn't running any driver programs, so this really isn't something we can address in this project.

More generally, the CUPS architecture has been moving towards running both CUPS/cupsd itself and legacy driver software in containers. The driver software is encapsulated in "Printer Applications", which can run in a variety of containerized environments. Modern printers just use IPP and don't need any of that driver nonsense...
